create extension if not exists vector;

create table if not exists public.job_seoul_50 (
  id bigint generated by default as identity primary key,
  ann_no bigint not null,
  title text,
  company_or_org text,
  business_type_code text,
  business_type_name text,
  recruit_status_code text,
  recruit_status_name text,
  recruit_type_code text,
  recruit_type_name text,
  apply_period text,
  apply_start text,
  apply_end text,
  dday integer,
  recruit_count integer,
  occupation_code text,
  occupation_name text,
  work_condition_code text,
  work_condition_name text,
  career_code text,
  career_name text,
  pay_hourly numeric,
  pay_text text,
  event_date_start text,
  event_date_end text,
  event_location text,
  pre_edu_yn text,
  source_url text,
  embedding vector(1536),
  crawled_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.job_seoul_50
  add column if not exists embedding vector(1536);

create unique index if not exists job_seoul_50_ann_no_key
  on public.job_seoul_50 (ann_no);

create index if not exists job_seoul_50_title_idx
  on public.job_seoul_50 (title);

create index if not exists job_seoul_50_business_type_code_idx
  on public.job_seoul_50 (business_type_code);

create index if not exists job_seoul_50_recruit_status_code_idx
  on public.job_seoul_50 (recruit_status_code);

create index if not exists job_seoul_50_occupation_name_idx
  on public.job_seoul_50 (occupation_name);

create index if not exists job_seoul_50_embedding_hnsw_idx
  on public.job_seoul_50
  using hnsw (embedding vector_cosine_ops);

create or replace function public.set_job_seoul_50_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_job_seoul_50_updated_at on public.job_seoul_50;

create trigger set_job_seoul_50_updated_at
before update on public.job_seoul_50
for each row
execute function public.set_job_seoul_50_updated_at();

alter table public.job_seoul_50 disable row level security;

notify pgrst, 'reload schema';
