create extension if not exists vector;

create table if not exists public.education (
  id bigint generated by default as identity primary key,
  ann_no bigint not null,
  category text,
  recruitment_status text,
  title text,
  provider text,
  business_type_code text,
  business_type_name text,
  recruit_status_code text,
  recruit_status_name text,
  recruit_type_code text,
  recruit_type_name text,
  apply_period text,
  apply_start text,
  apply_end text,
  selection_announcement text,
  dday integer,
  recruit_count integer,
  occupation_code text,
  occupation_name text,
  work_condition_code text,
  work_condition_name text,
  career_code text,
  career_name text,
  fee_amount numeric,
  fee_text text,
  education_start text,
  education_end text,
  education_location text,
  pre_edu_yn text,
  application_url text,
  source_url text,
  content text,
  embedding vector(1536),
  crawled_at timestamptz,
  raw_data jsonb not null default '{}'::jsonb,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.education
  add column if not exists category text,
  add column if not exists recruitment_status text,
  add column if not exists application_url text;

update public.education
set application_url = source_url
where application_url is null
  and source_url is not null;

update public.education
set category = case
    when business_type_code = 'AI_DIGITAL'
      or source_url like '%educationKind=aiDigital%' then 'AI디지털교육'
    when business_type_code = 'CENTER_EDUCATION'
      or source_url like '%educationKind=centerEducation%' then '50플러스센터교육'
    when business_type_code = 'IN49009'
      or business_type_name = '직업훈련'
      or source_url like '%in_appView.do%' then '취업훈련'
    else category
  end
where category is null
  or category = '';

update public.education
set recruitment_status = case
    when recruit_status_name in ('모집중', '신청·접수중', '신청ㆍ접수중') then '모집중'
    when recruit_status_name = '모집예정' then '모집예정'
    when recruit_status_name in ('모집마감', '마감') then '모집마감'
    when recruit_status_code in ('PENDING', 'PEND') then '모집예정'
    when recruit_status_code in ('OPEN', 'WAITING', 'IN17003') then '모집중'
    when recruit_status_code in ('CLOSED', 'CLOSE') then '모집마감'
    else recruitment_status
  end
where recruitment_status is null
  or recruitment_status = '';

drop index if exists public.education_ann_no_key;

create index if not exists education_ann_no_idx
  on public.education (ann_no);

create unique index if not exists education_application_url_key
  on public.education (application_url);

create index if not exists education_category_idx
  on public.education (category);

create index if not exists education_recruitment_status_idx
  on public.education (recruitment_status);

create index if not exists education_title_idx
  on public.education (title);

create index if not exists education_recruit_status_code_idx
  on public.education (recruit_status_code);

create index if not exists education_business_type_code_idx
  on public.education (business_type_code);

create index if not exists education_occupation_name_idx
  on public.education (occupation_name);

create index if not exists education_embedding_hnsw_idx
  on public.education
  using hnsw (embedding vector_cosine_ops);

create or replace function public.set_education_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_education_updated_at on public.education;

create trigger set_education_updated_at
before update on public.education
for each row
execute function public.set_education_updated_at();

alter table public.education disable row level security;

notify pgrst, 'reload schema';
